### ISSUE TITLE
KJIJKPlayer 引入有问题，即使引入头文件还是找不到

### ISSUE THREAD

**Issue by zixingxuan** [yangKJ/KJPlayerDemo#5]
提示这个：Property with 'retain (or strong)' attribute must be of object type

**Comment by yangKJ** [comment]
这个需要引入 IJKMediaFramework 库，才能正常使用。

**Comment by zeqinjie** [comment]
+1 demo 执行 install 确实含 IJKMediaFramework 库，依然报错。
